package constantes;

public class Vues {

    public static final String CONSTANTE_VUE_CONNEXION                                      = "/WEB-INF/connexion.jsp";
    public static final String CONSTANTE_VUE_CONNEXION_NOMCOURT                             = "connexion";
    public static final String CONSTANTE_VUE_CONNEXION_DESCRIPTION                          = "Page de connexion";
    public static final String CONSTANTE_VUE_INSCRIPTION                                    = "/WEB-INF/inscription.jsp";
    public static final String CONSTANTE_VUE_INSCRIPTION_NOMCOURT                           = "inscription";
    public static final String CONSTANTE_VUE_INSCRIPTION_DESCRIPTION                        = "Créer un profil";
    public static final String CONSTANTE_VUE_HOME                                           = "/WEB-INF/home.jsp";
    public static final String CONSTANTE_VUE_HOME_NOMCOURT                                  = "home";
    public static final String CONSTANTE_VUE_HOME_DESCRIPTION                               = "HomePage";
    public static final String CONSTANTE_VUE_PROFIL                                         = "/WEB-INF/profil.jsp";
    public static final String CONSTANTE_VUE_PROFIL_NOMCOURT                                = "profil";
    public static final String CONSTANTE_VUE_PROFIL_DESCRIPTION                             = "Votre profil";
    public static final String CONSTANTE_VUE_MENU                                           = "/WEB-INF/menu.jsp";
    public static final String CONSTANTE_VUE_DECONNEXION                                    = "/WEB-INF/deconnexion.jsp";
    public static final String CONSTANTE_VUE_DECONNEXION_NOMCOURT                           = "deconnexion";
    public static final String CONSTANTE_VUE_DECONNEXION_DESCRIPTION                        = "Page de deconnexion";
    public static final String CONSTANTE_VUE_DECONNEXIONBOUTON                              = "/WEB-INF/deconnexionbouton.jsp";
    public static final String CONSTANTE_VUE_DECONNEXIONBOUTON_NOMCOURT                     = "deconnexionbouton";
    public static final String CONSTANTE_VUE_DECONNEXIONBOUTON_DESCRIPTION                  = "Bouton de deconnexion";
    public static final String CONSTANTE_VUE_ADMINISTRATION                                 = "/WEB-INF/administration.jsp";
    public static final String CONSTANTE_VUE_ADMINISTRATION_NOMCOURT                        = "administration";
    public static final String CONSTANTE_VUE_ADMINISTRATION_DESCRIPTION                     = "Administration";
    public static final String CONSTANTE_VUE_CREERSCRIPT                                    = "/WEB-INF/creerscript.jsp";
    public static final String CONSTANTE_VUE_CREERSCRIPT_NOMCOURT                           = "creerscript";
    public static final String CONSTANTE_VUE_CREERSCRIPT_DESCRIPTION                        = "Creer un script";
    public static final String CONSTANTE_VUE_LISTESCRIPTS                                   = "/WEB-INF/listescripts.jsp";
    public static final String CONSTANTE_VUE_LISTESCRIPTS_NOMCOURT                          = "listescripts";
    public static final String CONSTANTE_VUE_LISTESCRIPTS_DESCRIPTION                       = "Gérer les scripts";
    public static final String CONSTANTE_VUE_ENVOIFICHIERS                                  = "/WEB-INF/envoifichiers.jsp";
    public static final String CONSTANTE_VUE_ENVOIFICHIERS_NOMCOURT                         = "envoifichiers";
    public static final String CONSTANTE_VUE_ENVOIFICHIERS_DESCRIPTION                      = "Envoyer un ou des fichiers";
    public static final String CONSTANTE_VUE_GERERFICHIERS                                  = "/WEB-INF/gererfichiers.jsp";
    public static final String CONSTANTE_VUE_GERERFICHIERS_NOMCOURT                         = "gererfichiers";
    public static final String CONSTANTE_VUE_GERERFICHIERS_DESCRIPTION                      = "Gérer les fichiers uploadés";
    public static final String CONSTANTE_VUE_LECTUREFICHIER                                 = "/WEB-INF/lecturefichier.jsp";
    public static final String CONSTANTE_VUE_LECTUREFICHIER_NOMCOURT                        = "lecturefichier";
    public static final String CONSTANTE_VUE_LECTUREFICHIER_DESCRIPTION                     = "Lire un fichier texte et l'écrire dans un autre";
    public static final String CONSTANTE_VUE_ECRITUREFICHIER                                = "/WEB-INF/ecrirefichier.jsp";
    public static final String CONSTANTE_VUE_ECRITUREFICHIER_NOMCOURT                       = "ecrirefichier";
    public static final String CONSTANTE_VUE_ECRITUREFICHIER_DESCRIPTION                    = "Ecrire dans un fichier";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXT                       = "/WEB-INF/ecriregenererfichiertext.jsp";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXT_NOMCOURT              = "ecriregenererfichiertext";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXT_DESCRIPTION           = "Ecrire et générer le résultat dans un fichier text";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXTFILEWRITER             = "/WEB-INF/ecriregenererfichiertextfilewriter.jsp";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXTFILEWRITER_NOMCOURT    = "ecriregenererfichiertextfilewriter";
    public static final String CONSTANTE_VUE_ECRIREGENERERFICHIERTEXTFILEWRITER_DESCRIPTION = "Ecrire et générer le résultat dans un fichier text avec file writer";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILEREADER                      = "/WEB-INF/lecteurfichierfilereader.jsp";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILEREADER_NOMCOURT             = "lecteurfichierfilereader";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILEREADER_DESCRIPTION          = "Lire un fichier avec file reader";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILECHANNEL                     = "/WEB-INF/lecteurfichierfilechannel.jsp";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILECHANNEL_NOMCOURT            = "lecteurfichierfilechannel";
    public static final String CONSTANTE_VUE_LIREFICHIERAVECFILECHANNEL_DESCRIPTION         = "Lire un fichier avec filechannel";
}
